import fs from 'fs'
import path from 'path'

/**
 * Owns only the temporary clip outputs generated by `cut-video-clips`.
 * Source media may legitimately live in the same directory (for example the
 * user-facing `fuente_recortada.mp4`), so it is never part of broad cleanup.
 */
export const ORIGINAL_CLIP_OUTPUT_PATTERN = /^clip_\d+\.mp4$/i

export class OriginalClipSegmentationError extends Error {
  constructor(public code: string, message: string, public details: Record<string, unknown> = {}) {
    super(message)
    this.name = 'OriginalClipSegmentationError'
  }
}

function fail(code: string, message: string, details: Record<string, unknown> = {}): never {
  throw new OriginalClipSegmentationError(code, message, details)
}

function canonical(candidate: string): string {
  return path.resolve(candidate).toLocaleLowerCase('en-US')
}

function isSamePath(left: string, right: string): boolean {
  return canonical(left) === canonical(right)
}

async function assertUsableInput(inputPath: unknown): Promise<string> {
  if (typeof inputPath !== 'string' || !inputPath.trim())
    fail('ORIGINAL_SEGMENT_INPUT_REQUIRED', 'La segmentación requiere un video de entrada explícito')
  const input = path.resolve(inputPath)
  let stat: fs.Stats
  try {
    stat = await fs.promises.lstat(input)
  } catch (error: any) {
    if (error?.code === 'ENOENT')
      fail('ORIGINAL_SEGMENT_INPUT_MISSING', 'El video de entrada no existe', { input })
    throw error
  }
  if (stat.isSymbolicLink() || !stat.isFile())
    fail('ORIGINAL_SEGMENT_INPUT_INVALID', 'El video de entrada debe ser un archivo regular', { input })
  return input
}

export type PrepareOriginalClipSegmentationResult = {
  inputPath: string
  outputDir: string
  removedClipOutputs: string[]
  preservedInputInsideOutputDir: boolean
}

/**
 * Verifies the source before mutating the output directory, then removes only
 * stale `clip_###.mp4` files made by this segmenter. It deliberately retains
 * every foreign file and never unlinks the current input, even if a caller
 * happens to use an output-looking filename as input.
 */
export async function prepareOriginalClipSegmentation(input: {
  inputPath: unknown
  outputDir: unknown
}): Promise<PrepareOriginalClipSegmentationResult> {
  if (typeof input.outputDir !== 'string' || !input.outputDir.trim())
    fail('ORIGINAL_SEGMENT_OUTPUT_REQUIRED', 'La segmentación requiere un directorio de salida explícito')

  // This ordering is the safety property: a missing input must leave previous
  // clip outputs untouched instead of first erasing the only usable material.
  const inputPath = await assertUsableInput(input.inputPath)
  const outputDir = path.resolve(input.outputDir)
  await fs.promises.mkdir(outputDir, { recursive: true })

  const removedClipOutputs: string[] = []
  for (const entry of await fs.promises.readdir(outputDir, { withFileTypes: true })) {
    if (!entry.isFile() || !ORIGINAL_CLIP_OUTPUT_PATTERN.test(entry.name)) continue
    const candidate = path.join(outputDir, entry.name)
    if (isSamePath(candidate, inputPath)) continue
    await fs.promises.unlink(candidate)
    removedClipOutputs.push(candidate)
  }

  return {
    inputPath,
    outputDir,
    removedClipOutputs: removedClipOutputs.sort((a, b) => a.localeCompare(b, 'en')),
    preservedInputInsideOutputDir: isSamePath(path.dirname(inputPath), outputDir),
  }
}
