// Isolated V2 finish acceptance: productive resolver -> ProjectAssets -> SceneSpec -> V15 -> DPI-safe capture -> MP4.
const {app,session,ipcMain}=require('electron')
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict')
const crypto=require('node:crypto')
const {spawnSync}=require('node:child_process')
const {createTestFixture,cleanupTestFixture}=require('../../helpers/safe-fixture')
const root=path.resolve(__dirname,'../../..')
const packageRoot=path.resolve(root,'../_cipher-idea-assembly-v2')
const runtime=path.join(packageRoot,'runtime')
const run=path.join(packageRoot,'runs',`run-${new Date().toISOString().replace(/[-:]/g,'').replace(/\..*/, '').replace('T','-')}`)
const fixture=createTestFixture('editorial-idea-assembly-v2')
const project=path.join(fixture,'project')
const ffmpeg=process.env.CIPHER_FFMPEG_EXE||'ffmpeg'
app.setPath('userData',path.join(fixture,'userData'))
app.commandLine.appendSwitch('force-device-scale-factor','1')
process.chdir(fixture)

const write=(name,data)=>{const file=path.join(run,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data);return file}
function ff(args){const r=spawnSync(ffmpeg,['-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',timeout:300000});if(r.status!==0)throw Error(`FFMPEG:${r.status}:${r.error?.message||r.stderr}`)}
function still(video,t,name){const target=path.join(run,name);fs.mkdirSync(path.dirname(target),{recursive:true});ff(['-ss',String(t),'-i',video,'-frames:v','1','-update','1',target]);return target}
function hstack(before,after,name){const target=path.join(run,name);ff(['-i',before,'-i',after,'-filter_complex','hstack=inputs=2','-frames:v','1','-update','1',target]);return target}
function publish(b,name){const bytes=fs.readFileSync(path.join(runtime,`${name}.png`));const p=b.publishRasterProjectAssetV1({projectRoot:project,provider:'editorial-pilot-raster',assetId:`idea-v2-${name}`,bytes,requireUsefulAlpha:name!=='paper-background',source:{providerVersion:'chatgpt-imagegen-2026-09',attribution:'Generated specifically for IDEA assembly V2 finish'},validationRevision:'editorial-idea-pilot-raster-v2'});return {asset:p.asset,bytes}}
function context(b,hero){const duration=80/24,sceneId='idea-assembly-v2-synthetic';const localSemantic=b.createLocalSceneSemanticV1({sceneId,start:0,end:duration,transcriptSegments:[{start:0,end:duration,text:'Una idea abre nuevas posibilidades'}],concepts:[{label:'idea',canonicalHint:'idea',start:0,end:duration,scope:'scene'}],anchor:'idea',globalText:'Una idea abre nuevas posibilidades',globalHints:[],globalContextRef:'synthetic:editorial-idea-assembly-v2'});return b.createModernVisualGenerationContextV2({sceneId,duration,localSemantic,keywordCandidates:[{keyword:'IDEA',source:'scene-semantic'}],preferredVisualMode:'asset-led',sistema:'editorial',direction:{fondo:'ondas',estructura:'marcoPoster',camara:'quieto',densidad:'alta',ritmo:'simultaneo',semilla:91551},videoStyleId:'cream-editorial',presentationProfile:b.EDITORIAL_EXPLAINER_V3,lockedChoices:[{slotId:'hero',concept:'idea',provider:'editorial-pilot-raster',representation:'photo-cutout',reason:'EXPLICIT_IDEA_PILOT_CHATGPT_GENERATED',score:3,assetId:hero.asset.id,relativeFile:hero.asset.relativeFile,sha256:hero.asset.sha256,mime:hero.asset.mime,bounds:b.subjectBoundsFromPixabayRasterV1(hero.bytes),kind:'photo-cutout',alphaMode:'useful-alpha'}],colorPalettePlan:{version:1,primaryFamily:'blue-tech',compatibleFamilies:[],revision:b.COLOR_PALETTE_REVISION_V1}})}
async function render(b,compiled,format){const vertical=format==='vertical',width=vertical?720:1280,height=vertical?1280:720;let qc;const source=await b.renderGraphicClip(compiled.graphicData,{ancho:width,alto:height,fps:24,duracion:80/24,modo:'pantalla',sistema:'editorial',projectRoot:project,renderBindings:compiled.renderBindings,onQcReport:v=>qc=v,onQcFailure:v=>qc=v});assert(source&&fs.existsSync(source),`VISUAL_SIN_FICHERO:${format}:${JSON.stringify(qc?.findings)}`);assert.equal(qc?.findings.filter(x=>x.level==='error').length,0,JSON.stringify(qc?.findings));assert(qc.localTextContrast>=4.5,`IDEA_V2_CONTRAST=${qc.localTextContrast}`);const dest=path.join(run,`idea-assembly-v2-${format}.mp4`);fs.mkdirSync(run,{recursive:true});fs.copyFileSync(source,dest);const frames={};for(const [label,t] of Object.entries({first:0,assembly:.72,supports:1.67,stable:2.55,reading:2.90,exit:3.18}))frames[label]=still(dest,t,`frames/idea-assembly-v2-${format}-${label}.png`);return {mp4:dest,frames,qc:qc.findings,localTextContrast:qc.localTextContrast,width,height,framesExpected:80}}
function htmlCell(file,label){return `<figure><img src="${path.relative(run,file).replace(/\\/g,'/')}" alt=""><figcaption>${label}</figcaption></figure>`}

app.whenReady().then(async()=>{let exitCode=1;try{
  global.fetch=()=>{throw Error('NETWORK_FORBIDDEN_AFTER_MATERIALIZATION')};session.defaultSession.webRequest.onBeforeRequest((d,cb)=>cb({cancel:/^https?:/i.test(d.url)}));const b=require(path.join(root,'dist-electron/main/index.js'));ipcMain.removeHandler('get-elevenlabs-voices');ipcMain.handle('get-elevenlabs-voices',()=>({success:true,voices:[]}));b.createProjectFiles(project,{id:'idea-assembly-v2-synthetic',clips:[],timelineVideoClips:[],aiScript:'synthetic one-scene V2 finish'});
  const names=['bust','bulb','collage-rear','accent-paper','collage-front-neutral','personas-v2','datos','soluciones','impacto','paper-background'];const published=Object.fromEntries(names.map(name=>[name,publish(b,name)]));const batch=await b.resolveModernVisualGenerationBatchV2({contexts:[context(b,published.bust)],projectRoot:project});const base=batch[0].resolved.compiled;const historicalBaseIdentity=b.sceneSpecPixelIdentityAny(base.sceneSpec);const historicalBaseBytes=JSON.stringify(base.sceneSpec);
  const assets={hero:published.bust,supports:[published['personas-v2'],published.datos,published.soluciones,published.impacto],resources:{'idea-background':published['paper-background'],'idea-rear':published['collage-rear'],'idea-accent':published['accent-paper'],'idea-bulb':published.bulb,'idea-front':published['collage-front-neutral']}};
  const compile=theme=>b.compileEditorialIdeaAssemblyPilotV2({base,assets,accentTheme:theme});const orange=compile('orange');assert.equal(orange.sceneSpec.presentationProfile.revision,b.EDITORIAL_IDEA_ASSEMBLY_V2.revision);assert.deepEqual(orange.sceneSpec.layout,b.createIdeaAssemblyLayoutV2('portrait'));assert.notDeepEqual(orange.sceneSpec.layout,b.createIdeaAssemblyLayoutV1('portrait'));assert.equal(b.sceneSpecPixelIdentityAny(orange.sceneSpec),b.sceneSpecPixelIdentityAny(compile('orange').sceneSpec));assert.equal(b.sceneSpecPixelIdentityAny(base.sceneSpec),historicalBaseIdentity);assert.equal(JSON.stringify(base.sceneSpec),historicalBaseBytes);assert.equal(orange.sceneSpec.slots.length,5);assert.equal(orange.sceneSpec.ideaAssembly.resources.length,5);assert.equal(orange.sceneSpec.ideaAssembly.resources.find(v=>v.id==='idea-bulb').rect.y,-5);assert.equal(orange.sceneSpec.ideaAssembly.resources.find(v=>v.id==='idea-front').rect.height,31);assert(orange.sceneSpec.ideaAssembly.supports.at(-1).enter+.12<=.49);assert.notEqual(b.sceneSpecPixelIdentityAny(orange.sceneSpec),b.sceneSpecPixelIdentityAny(compile('teal').sceneSpec));
  const vertical=await render(b,orange,'vertical');const replay=await b.renderGraphicClip(orange.graphicData,{ancho:720,alto:1280,fps:24,duracion:80/24,modo:'pantalla',sistema:'editorial',projectRoot:project,renderBindings:orange.renderBindings});const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');assert(replay&&fs.existsSync(replay));assert.equal(sha(replay),sha(vertical.mp4));const horizontal=await render(b,orange,'horizontal');
  const v1Root=path.resolve(root,'../_cipher-idea-assembly-v1/runs/run-20260922-020524/frames');const beforeVertical=path.join(v1Root,'idea-orange-vertical-stable.png'),beforeHorizontal=path.join(v1Root,'idea-orange-horizontal-stable.png');const comparisons={};if(fs.existsSync(beforeVertical))comparisons.vertical=hstack(beforeVertical,vertical.frames.stable,'comparison-v1-v2-vertical-stable.png');if(fs.existsSync(beforeHorizontal))comparisons.horizontal=hstack(beforeHorizontal,horizontal.frames.stable,'comparison-v1-v2-horizontal-stable.png');
  const style='<style>body{background:#24221f;color:#f4f2ed;font:16px Arial;padding:24px}main{display:grid;grid-template-columns:repeat(2,minmax(260px,1fr));gap:16px}figure{margin:0;background:#33302c;padding:10px}img{width:100%;max-height:850px;object-fit:contain;background:#f0eee8}figcaption{margin-top:8px}</style>';write('assembly-keyframes.html',`<!doctype html><meta charset="utf-8">${style}<h1>IDEA assembly V2 · 80 frames / 24 fps</h1><main>${Object.entries(vertical.frames).map(([label,file])=>htmlCell(file,`vertical ${label}`)).join('')}${Object.entries(horizontal.frames).map(([label,file])=>htmlCell(file,`horizontal ${label}`)).join('')}</main>`);write('comparison-v1-v2.html',`<!doctype html><meta charset="utf-8">${style}<h1>IDEA stable · V1 left / V2 right</h1><p>Mismos recursos salvo PERSONAS; V2 cambia revisión, geometría, recorridos y tipografía.</p><main>${Object.entries(comparisons).map(([name,file])=>htmlCell(file,name)).join('')}</main>`);
  const evidence={branch:'v15-editorial-idea-assembly-v1',profile:orange.sceneSpec.presentationProfile,synthetic:true,source:'ChatGPT image generation',frames:80,fps:24,durationSeconds:80/24,assets:names.map(name=>({name,sha256:published[name].asset.sha256,alphaUseful:published[name].asset.validation.alphaUseful})),sceneSpec:orange.sceneSpec,renderBindings:orange.renderBindings,identity:b.sceneSpecPixelIdentityAny(orange.sceneSpec),render:{vertical,horizontal},comparison:comparisons,visualSinFichero:0,offlineAfterMaterialization:true};write('evidence.json',JSON.stringify(evidence,null,2));const debugFile=path.join(fixture,'cipher-studio','generation-debug.log');if(fs.existsSync(debugFile))assert(!/FUENTE AUSENTE|fonts\.load lanzo/iu.test(fs.readFileSync(debugFile,'utf8')),'FONT_LOAD_FAILURE');console.log(`IDEA_ASSEMBLY_V2_PASS:${run}`);exitCode=0
}catch(e){console.error('IDEA_ASSEMBLY_V2_FAIL',e.stack||e);console.error('IDEA_ASSEMBLY_V2_FIXTURE_ON_FAILURE',fixture)}finally{if(exitCode===0)cleanupTestFixture(fixture);app.exit(exitCode)}}).catch(e=>{console.error(e);app.exit(1)})
