// Twelve directed scenes, two per existing family. The words, assets and
// relations are explicitly curated; no relationship is inferred from layout.
module.exports=[
  {id:'F01',family:'marcoPoster',composition:'base',hero:'H001',supports:['S001','S002','S003','S004'],
    title:['UNA','IDEA','personas y datos construyen soluciones con impacto'],
    relations:[['support-1','hero','informs'],['support-2','hero','informs'],
      ['hero','support-3','causes'],['hero','support-4','causes']],
    display:'Fraunces',color:'#A83B19',recipe:'arrow',response:'accent',ambient:'discreto'},
  {id:'F02',family:'marcoPoster',composition:'focus',hero:'H011',supports:['S005','S006','S025'],
    title:['LA','SEÑAL','la cámara capta; la red comunica'],
    relations:[['support-1','hero','informs'],['hero','support-2','transfers'],
      ['hero','support-3','connects']],
    display:'Instrument Serif',color:'#238C87',recipe:'dotted',response:'halo',ambient:'off'},
  {id:'F03',family:'editorial',composition:'base',title:['PENSAR','DISTINTO','también es una herramienta'],
    display:'Fraunces',color:'#A83B19',ambient:'off'},
  {id:'F04',family:'editorial',composition:'focus',title:['EL','CAMBIO','empieza con una pregunta'],
    display:'Bricolage Grotesque',color:'#238C87',ambient:'off'},
  {id:'F05',family:'partidoVertical',composition:'base',hero:'H025',supports:['S040','S042','S021'],
    title:['LA','RED','conecta cómputo y nube con seguridad'],
    relations:[['support-1','hero','connects'],['hero','support-2','connects'],
      ['support-3','hero','informs']],
    display:'Bricolage Grotesque',color:'#238C87',recipe:'accent-link',response:'scale',ambient:'discreto'},
  {id:'F06',family:'partidoVertical',composition:'focus',hero:'H121',supports:['S043','S045'],
    title:['EL','AHORRO','se compara con la economía y el intercambio'],
    relations:[['support-1','hero','informs'],['hero','support-2','compares']],
    display:'Fraunces',color:'#B8444F',recipe:'dotted',response:'scale',ambient:'off'},
  {id:'F07',family:'cuaderno',composition:'base',hero:'H006',supports:['S014','S015','S019'],
    title:['LA','ESCRITURA','conserva memoria, creatividad y validación'],
    relations:[['hero','support-1','connects'],['support-2','hero','informs'],
      ['support-3','hero','informs']],
    display:'Instrument Serif',color:'#A83B19',recipe:'arrow',response:'pulse',ambient:'discreto'},
  {id:'F08',family:'cuaderno',composition:'focus',hero:'H132',supports:['S013','S014'],
    title:['LA','ARQUEOLOGÍA','investiga rastros de la memoria'],
    relations:[['support-1','hero','informs'],['hero','support-2','connects']],
    display:'Fraunces',color:'#B8444F',recipe:'dotted',response:'halo',ambient:'off'},
  {id:'F09',family:'constelacion',composition:'base',hero:'H025',supports:['S009','S025','S040','S042'],
    title:['UNA','RED','conexión, comunicación, cómputo y nube'],
    relations:[['support-1','hero','connects'],['hero','support-2','connects'],
      ['support-3','hero','connects'],['hero','support-4','connects']],
    display:'Fraunces',color:'#238C87',recipe:'accent-link',response:'halo',ambient:'discreto'},
  {id:'F10',family:'constelacion',composition:'focus',hero:'H041',supports:['S001','S009','S019'],
    title:['LA','COLABORACIÓN','vincula personas, conexión y validación'],
    relations:[['support-1','hero','connects'],['hero','support-2','connects'],
      ['support-3','hero','informs']],
    display:'Instrument Serif',color:'#7B4EA3',recipe:'dot-flow',response:'accent',ambient:'off'},
  {id:'F11',family:'cascada',composition:'base',hero:'H101',supports:['S049','S050','S048'],
    title:['LAS','PIEZAS','herramientas y construcción alcanzan calidad'],
    relations:[['support-1','hero','causes'],['hero','support-2','causes'],
      ['support-2','support-3','causes']],
    display:'Bricolage Grotesque',color:'#A83B19',recipe:'dot-flow',response:'scale',ambient:'discreto'},
  {id:'F12',family:'cascada',composition:'focus',hero:'H061',supports:['S033','S034','S036'],
    title:['UNA','SEMILLA','agua, naturaleza y clima favorecen germinación'],
    relations:[['support-1','hero','causes'],['support-2','hero','informs'],
      ['support-3','hero','informs']],
    display:'Fraunces',color:'#238C87',recipe:'light-pulse',response:'pulse',ambient:'off'},
]
